# Data
data:
  # Option A: CSV files with columns path,label
  train_csv: null  # e.g., data/processed/train.csv
  val_csv: null    # e.g., data/processed/val.csv
  test_csv: null   # e.g., data/processed/test.csv

  # Option B: folder with normal/ and pneumonia/ subfolders
  image_root: null # e.g., data/processed/images

  image_size: 448

# Model
model:
  name: resnet18   # resnet18 | resnet34 | efficientnet_b0
  pretrained: true

# Loss
loss:
  name: focal      # bce | focal
  params:
    gamma: 2.0

# Train
train:
  batch_size: 32
  num_workers: 4
  lr: 0.0003
  weight_decay: 0.0001
  epochs: 5
  scheduler: cosine
  aug: medical     # none | light | medium | medical
  sampler: weighted  # none | weighted
  class_weight: auto # none | auto (auto: N_total/(K*N_i) for i in class)

# Misc
seed: 42
output_dir: experiments
